### PR TITLE
WIP: Prepare for Qiskit 1.0

### PR DESCRIPTION
**Pull request by wshanks**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by wshanks** [comment]
This is just to test in preparation for Qiskit 1.0 which merge the `qiskit` and `qiskit-terra` PyPI packages, so the `qiskit` package will be like what `qiskit-terra` was before and `qiskit-terra` will stop getting updates. So this PR mostly copies the recipe from the qiskit-terra feedstock. I don't think we need to merge this as a beta release, but I wanted to start testing. When 1.0.0 is released, we can update the version and SHA here and make this the update PR, or we can close this in favor of a separate update PR.

One thing I realized from making this PR is that we will need to run through the Python 3.12, PyPy, and OSX ARM64 migrations again. I thought about copying those config files from the qiskit-terra feedstock, but I think it is cleaner just to do the migrations again.

**Comment by BastianZim** [comment]
> One thing I realized from making this PR is that we will need to run through the Python 3.12, PyPy, and OSX ARM64 migrations again. I thought about copying those config files from the qiskit-terra feedstock, but I think it is cleaner just to do the migrations again.

Yes, it‘s probably better to do that. The ARM64 migration needs to be kicked off by adding the name to the config file but I can do that when ready.

**Comment by wshanks** [comment]
@BastianZim I removed the overlinking error from the config which is how qiskit-terra-feedstock was configured. Is there no better workaround?

After that, we hit an error with symengine. I think this is a new one (in qiskit-terra-feedstock we were always restricted to python-symengine<0.10). I opened https://github.com/conda-forge/python-symengine-feedstock/issues/50 for it.

**Comment by BastianZim** [comment]
> Is there no better workaround?

It can be a false positive but I would wait until you get some feedback on the issue. I'm not super familiar with over linking so it might make sense to post in the group chat as well.

**Comment by wshanks** [comment]
Superseded by #12.

**Pull request closed without merging**
